### ISSUE TITLE
Dataset, Privacy Issue

### ISSUE THREAD

**Issue by kostjaigin** [donghyeonk/nets#2]
Hi! 

I was very inspired by your work "Learning User Preferences and Understanding Calendar Contexts for Event Scheduling". I read your answer to [this issue](https://github.com/dmis-lab/nesa/issues/1), so i know that due to the privacy reasons, you do not provide access to the dataset used in this research. Could it be that there exist some **reduced version of the original dataset** (e.g. without email addresses of corresponding users or with encoded personal information) that could be shared? 

Thank you, ..

**Comment by donghyeonk** [comment]
Hi, 
Sorry for late reply. 
Unfortunately, the company I was working for at the time went out of business, so I can't access that data anymore.
