### ISSUE TITLE
Could not download source

### ISSUE THREAD

**Issue by 729765827** [donghyeonk/nets#4]
hello, I found the download links are failed. Could you please upload the new one?
Failed links:
Download sample data
[sample_data.csv](http://gofile.me/6pN25/RzLIg9T9E)
Download word, character dictionaries
[dataset_180522_dict.pkl](http://gofile.me/6pN25/xCHU9Cmt3)
Download pretrained NESA model
[nesa_180522_0.pth](http://gofile.me/6pN25/nAZbCQ5cx)

**Comment by donghyeonk** [comment]
Hi, I can download the files now. Check your network DNS, site blockers.

**Comment by 729765827** [comment]
ok, the problem is solved, thank you for your help!
