### ISSUE TITLE
Training pickle data download unstable

### ISSUE THREAD

**Issue by lazargugleta** [donghyeonk/nets#5]
Hey,
I was trying to run the script using `python3 test.py`, but the training pickle is not complete.
Whenever I try to download it comes out a different size.
Finally I managed to get a download of 367MB  but still the data does not load correctly.
I get the following error:
```
CPU
Loading test dataset..
Creating the test dataset pickle..
./data/dataset_180522_dict.pkl
Traceback (most recent call last):
  File "/home/veloce/Documents/nesa/test.py", line 122, in <module>
    test_dataset = get_dataset(config, args.trained_dict_path)
  File "/home/veloce/Documents/nesa/test.py", line 14, in get_dataset
    nets_dictionary = pickle.load(open(trained_dict_path, 'rb'))
_pickle.UnpicklingError: pickle data was truncated
```
Would it be possible for you to upload it somewhere different?

**Comment by donghyeonk** [comment]
Hi @lazargugleta

If the size of dataset_180522_dict.pkl file is smaller than 359 MB, try downloading it again.

The NAS network connection is unstable, so sometimes file downloads seem to be interrupted. I'll move the repository of that file soon and fix the link.

**Comment by donghyeonk** [comment]
Hi @lazargugleta 

I uploaded data/dataset_180522_dict.pkl and data/nesa_180522_0.pth using Git LFS.

You should be able to get the whole file with just a "git pull".

**Comment by lazargugleta** [comment]
Works now. Thank you!
